---
fixtures:
  repositories:
    stdlib:
      ref: "4.24.0"
      repo: "https://github.com/puppetlabs/puppetlabs-stdlib"
    mysql:
      ref: "3.11.0"
      repo: "https://github.com/puppetlabs/puppetlabs-mysql"
    staging:
      ref: "v2.0.1"
      repo: "https://github.com/voxpupuli/puppet-staging"
    docker:
      ref: "1.0.5"
      repo: "https://github.com/puppetlabs/puppetlabs-docker"
    apt:
      ref: "4.2.0"
      repo: "https://github.com/puppetlabs/puppetlabs-apt"
    vision_mysql:
      ref: "origin/production"
      repo: "https://github.com/vision-it/vision-mysql"
    vision_docker:
      ref: "origin/production"
      repo: "https://github.com/vision-it/vision-docker"
    vision_shipit:
      ref: "production"
      repo: "https://github.com/vision-it/vision-shipit"
    vision_jenkins:
      ref: "production"
      repo: "https://github.com/vision-it/vision-jenkins"

  symlinks:
    vision_webshop: '#{source_dir}'
